version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
      - .vue
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_patterns:
- node_modules/
- build/
